[workspace]
resolver = "2"

members = [
    "common",
    "compiler",
    "compilerlib",
    "disassembler",
    "vm"
]


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
